//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jasonalinton.Database.Blog
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogpost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public blogpost()
        {
            this.blogposttags = new HashSet<blogposttag>();
        }
    
        public int idBlogPost { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public byte[] post { get; set; }
        public Nullable<int> postition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blogposttag> blogposttags { get; set; }
    }
}
