//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jasonalinton.Database.Blog
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogposttag
    {
        public int idBlogPostTags { get; set; }
        public int idBlogPost { get; set; }
        public int idTags { get; set; }
    
        public virtual blogpost blogpost { get; set; }
        public virtual tag tag { get; set; }
    }
}
